### ISSUE TITLE
The website.

### ISSUE THREAD

**Issue by hetbet** [Theohaines/the-television-of-babel#2]
It needs a redesign

![image](https://github.com/Theohaines/the-television-of-babel/assets/114992138/11df589c-5213-444d-b8f2-d7e5f66623ae)
![image](https://github.com/Theohaines/the-television-of-babel/assets/114992138/139e975f-7202-40ca-b3d3-0185757186f3)

**Comment by wilsoncrunden** [comment]
@Theohaines
